<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
final class WPVDMCP_Parity_Fields {
	const OPTION='wpvdmcp_editable_fields';
	const FIELD_TYPES=array('text','textarea','number','email','url','date','checkbox','color','image','gallery','wysiwyg','post_select','repeater');
	const SETTING_TYPES=array('text','textarea','number','email','url','date','checkbox','color','image','wysiwyg');
	public static function bootstrap(){add_action('init',array(__CLASS__,'replay'),12);}
	public static function definitions(){return array(
		self::tool('list_editable_fields','List editable fields, groups, and settings persisted by Direct MCP and replayed through WPVibe native field APIs.',array()),
		self::tool('register_editable_field','Persist and register a WPVibe editable post-meta field. Requires one-time browser approval.',array('post_type'=>self::strp('Post type.',true),'key'=>self::strp('Meta key.',true),'config'=>self::objp('WPVibe field config.',true),'approval_id'=>self::strp('One-time approval ID.'))),
		self::tool('register_editable_group','Persist a WPVibe editable-field meta-box group. Requires approval.',array('post_type'=>self::strp('Post type.',true),'group_id'=>self::strp('Group ID.',true),'config'=>self::objp('Group config.',true),'approval_id'=>self::strp('One-time approval ID.'))),
		self::tool('register_editable_setting','Persist a WPVibe editable global setting. Requires approval.',array('key'=>self::strp('Setting key.',true),'config'=>self::objp('WPVibe setting config.',true),'approval_id'=>self::strp('One-time approval ID.'))),
		self::tool('validate_blocks','Validate Gutenberg-compatible blocks recursively against registered block schemas, including Kadence and GenerateBlocks when installed.',array('blocks'=>array('type'=>'array','description'=>'Parsed block objects.'),'content'=>self::strp('Optional serialized block markup to parse.'),'strict'=>array('type'=>'boolean','description'=>'Treat unknown blocks as errors.'))),
		self::tool('save_validated_blocks','Validate registered Gutenberg block schemas first, then update post content through WordPress REST only after one-time browser approval.',array('rest_path'=>self::strp('WordPress post REST path such as /wp/v2/pages/123.',true),'blocks'=>array('type'=>'array','description'=>'Parsed blocks to validate.'),'content'=>self::strp('Serialized block content to save.',true),'approval_id'=>self::strp('One-time approval ID.'))),
	);}
	public static function handles($name){foreach(self::definitions() as $d){if($d['name']===$name)return true;}return false;}
	public static function execute($name,$args){$args=is_array($args)?$args:array();switch($name){case'list_editable_fields':return self::list_all();case'register_editable_field':return self::write('field',$args);case'register_editable_group':return self::write('group',$args);case'register_editable_setting':return self::write('setting',$args);case'validate_blocks':return self::validate_blocks($args);case'save_validated_blocks':return self::save_validated_blocks($args);}return new WP_Error('unknown_fields_tool','Unknown fields/block tool.',array('status'=>404));}
	private static function list_all(){$d=get_option(self::OPTION,array());return array('field_types'=>self::FIELD_TYPES,'setting_types'=>self::SETTING_TYPES,'fields'=>array_values(isset($d['fields'])&&is_array($d['fields'])?$d['fields']:array()),'groups'=>array_values(isset($d['groups'])&&is_array($d['groups'])?$d['groups']:array()),'settings'=>array_values(isset($d['settings'])&&is_array($d['settings'])?$d['settings']:array()));}
	private static function write($kind,$args){$config=isset($args['config'])&&is_array($args['config'])?self::clean_config($args['config']):array();if('field'===$kind){$post_type=sanitize_key($args['post_type']??'');$key=sanitize_key($args['key']??'');if(!$post_type||!$key)return new WP_Error('invalid_field','post_type and key are required.',array('status'=>400));$type=$config['type']??'text';if(!in_array($type,self::FIELD_TYPES,true))return new WP_Error('invalid_field_type','Unsupported editable field type.',array('status'=>400,'allowed'=>self::FIELD_TYPES));$id=$post_type.':'.$key;$record=array('post_type'=>$post_type,'key'=>$key,'config'=>$config);}elseif('group'===$kind){$post_type=sanitize_key($args['post_type']??'');$group_id=sanitize_key($args['group_id']??'');if(!$post_type||!$group_id)return new WP_Error('invalid_group','post_type and group_id are required.',array('status'=>400));$id=$post_type.':'.$group_id;$record=array('post_type'=>$post_type,'group_id'=>$group_id,'config'=>$config);}else{$key=sanitize_key($args['key']??'');if(!$key)return new WP_Error('invalid_setting','key is required.',array('status'=>400));$type=$config['type']??'text';if(!in_array($type,self::SETTING_TYPES,true))return new WP_Error('invalid_setting_type','Unsupported editable setting type.',array('status'=>400,'allowed'=>self::SETTING_TYPES));$id=$key;$record=array('key'=>$key,'config'=>$config);} $payload=array('kind'=>$kind,'id'=>$id,'record'=>$record);$approval=self::approve('register_editable_'.$kind,$payload,$args);if(is_array($approval)||is_wp_error($approval))return $approval;$data=get_option(self::OPTION,array());if(!is_array($data))$data=array();$bucket=$kind.'s';if(!isset($data[$bucket])||!is_array($data[$bucket]))$data[$bucket]=array();$data[$bucket][$id]=$record;update_option(self::OPTION,$data,false);self::register_record($kind,$record);return array('status'=>'registered','kind'=>$kind,'record'=>$record,'persistent'=>true);}
	private static function approve($operation,$payload,$args){if(WPVDMCP_Approvals::bypass_enabled())return true;$id=isset($args['approval_id'])?(string)$args['approval_id']:'';if(!$id){$r=WPVDMCP_Approvals::request($operation,$payload,$operation);if(is_wp_error($r))return $r;return array_merge($r,array('status'=>'approval_required'));}return WPVDMCP_Approvals::consume($id,$operation,$payload);}
	private static function clean_config($config){$out=array();foreach(array('type','label','description','group','default','context','priority','title','options','sub_fields')as$k){if(array_key_exists($k,$config))$out[$k]=$config[$k];}if(isset($out['type']))$out['type']=sanitize_key($out['type']);foreach(array('label','description','group','context','priority','title')as$k){if(isset($out[$k]))$out[$k]=sanitize_text_field($out[$k]);}return $out;}
	public static function replay(){$data=get_option(self::OPTION,array());if(!is_array($data))return;foreach(array('groups'=>'group','fields'=>'field','settings'=>'setting')as$bucket=>$kind){foreach((array)($data[$bucket]??array())as$record)self::register_record($kind,$record);}}
	private static function register_record($kind,$r){if('field'===$kind&&function_exists('wpvibe_field_register'))return wpvibe_field_register($r['post_type'],$r['key'],$r['config']);if('group'===$kind&&function_exists('wpvibe_field_group_register'))return wpvibe_field_group_register($r['post_type'],$r['group_id'],$r['config']);if('setting'===$kind&&function_exists('wpvibe_setting_register'))return wpvibe_setting_register($r['key'],$r['config']);return true;}
	public static function block_types(){if(isset($GLOBALS['wpvdmcp_block_types'])&&is_array($GLOBALS['wpvdmcp_block_types']))return $GLOBALS['wpvdmcp_block_types'];$out=array();if(class_exists('WP_Block_Type_Registry')){foreach(WP_Block_Type_Registry::get_instance()->get_all_registered()as$name=>$obj)$out[$name]=array('attributes'=>is_array($obj->attributes)?$obj->attributes:array());}return $out;}
	private static function validate_blocks($args){$blocks=isset($args['blocks'])&&is_array($args['blocks'])?$args['blocks']:array();if(!$blocks&&!empty($args['content'])&&function_exists('parse_blocks'))$blocks=parse_blocks((string)$args['content']);$errors=array();$warnings=array();self::validate_list($blocks,self::block_types(),!empty($args['strict']),$errors,$warnings,'root');return array('valid'=>empty($errors),'errors'=>$errors,'warnings'=>$warnings,'checked_blocks'=>self::count_blocks($blocks));}
	private static function validate_list($blocks,$types,$strict,&$errors,&$warnings,$path){foreach((array)$blocks as$i=>$block){if(!is_array($block)){$errors[]=array('path'=>$path.'.'.$i,'message'=>'Block must be an object/array.');continue;}$name=(string)($block['blockName']??'');if(''===$name)continue;$p=$path.'.'.$i.'['.$name.']';if(!isset($types[$name])){if($strict)$errors[]=array('path'=>$p,'message'=>'Block is not registered on this site.');else$warnings[]=array('path'=>$p,'message'=>'Block is not registered on this site.');}else self::validate_attrs((array)($block['attrs']??array()),(array)($types[$name]['attributes']??array()),$p,$errors);self::validate_list((array)($block['innerBlocks']??array()),$types,$strict,$errors,$warnings,$p.'.innerBlocks');}}
	private static function validate_attrs($attrs,$schema,$path,&$errors){foreach($attrs as$key=>$value){if(!isset($schema[$key]))continue;$rule=(array)$schema[$key];if(isset($rule['enum'])&&!in_array($value,(array)$rule['enum'],true)){$errors[]=array('path'=>$path.'.attrs.'.$key,'message'=>'Value is outside the registered enum.');continue;}if(!empty($rule['type'])&&!self::matches_type($value,$rule['type']))$errors[]=array('path'=>$path.'.attrs.'.$key,'message'=>'Attribute type does not match registered schema.');}}
	private static function matches_type($v,$t){switch($t){case'string':return is_string($v);case'boolean':return is_bool($v);case'integer':return is_int($v);case'number':return is_int($v)||is_float($v);case'array':return is_array($v)&&(empty($v)||array_keys($v)===range(0,count($v)-1));case'object':return is_array($v);default:return true;}}
	private static function count_blocks($blocks){$n=0;foreach((array)$blocks as$b){if(is_array($b)){if(!empty($b['blockName']))$n++;$n+=self::count_blocks($b['innerBlocks']??array());}}return $n;}
	private static function save_validated_blocks($args){$path=(string)($args['rest_path']??'');$content=(string)($args['content']??'');if(!preg_match('#^/wp/v2/[a-z0-9_-]+/\d+$#i',$path))return new WP_Error('invalid_rest_path','Validated block writes are limited to WordPress post-type REST item routes.',array('status'=>400));$validation=self::validate_blocks(array('blocks'=>$args['blocks']??array(),'content'=>$content,'strict'=>true));if(empty($validation['valid']))return new WP_Error('invalid_blocks','Block validation failed; content was not written.',array('status'=>422,'validation'=>$validation));$payload=array('rest_path'=>$path,'content_hash'=>hash('sha256',$content),'checked_blocks'=>$validation['checked_blocks']);$approval=self::approve('save_validated_blocks',$payload,$args);if(is_array($approval)||is_wp_error($approval))return $approval;if(!WPVDMCP_Compatibility::route_exists($path))return new WP_Error('tool_unavailable','The requested WordPress REST item route is unavailable.',array('status'=>404));return WPVDMCP_Tools::dispatch('POST',$path,array(),array('content'=>$content));}
	private static function tool($name,$description,$props){$required=array();foreach($props as$k=>&$p){if(!empty($p['_required'])){$required[]=$k;unset($p['_required']);}}unset($p);$schema=array('type'=>'object','properties'=>(object)$props,'additionalProperties'=>false);if($required)$schema['required']=$required;return array('name'=>$name,'description'=>$description,'inputSchema'=>$schema);}private static function strp($d,$r=false){return array('type'=>'string','description'=>$d,'_required'=>$r);}private static function objp($d,$r=false){return array('type'=>'object','description'=>$d,'_required'=>$r);}
}
