<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
final class WPVDMCP_Parity_Skills {
	const OPTION='wpvdmcp_saved_skills';const MAX_SKILLS=50;const MAX_BYTES=20000;const MAX_REFERENCE_FILES=10;const MAX_REFERENCE_BYTES=50000;
	public static function extra_catalog(){$slugs=array('kadence'=>'Kadence Blocks','generatepress'=>'GeneratePress / GP Premium','generateblocks'=>'GenerateBlocks','editable-fields'=>'Editable fields','block-validation'=>'Validated block output','saved-skills'=>'Saved local skills','pdf-media'=>'PDF and media intelligence','site-intelligence'=>'Site intelligence','live-reload'=>'Live reload','lighthouse'=>'Lighthouse / performance audit providers','image-search'=>'Stock image search providers','abilities-plugin'=>'Abilities-first plugin workflow','rank-math'=>'Rank Math SEO','aioseo'=>'All in One SEO','seopress'=>'SEOPress','yoast-seo'=>'Yoast SEO','smash-balloon'=>'Smash Balloon','memberpress'=>'MemberPress','charitable'=>'Charitable','duplicator'=>'Duplicator','pushengage'=>'PushEngage','easy-digital-downloads'=>'Easy Digital Downloads','lifterlms'=>'LifterLMS','wpforms'=>'WPForms','kit-convertkit'=>'Kit / ConvertKit','modern-cart'=>'Modern Cart','cartflows'=>'CartFlows','pagelayer'=>'Pagelayer','elementskit'=>'ElementsKit','amelia'=>'Amelia / Booking for Appointments and Events Calendar','adtribes-product-feed'=>'Product Feed PRO by AdTribes','fluentcart'=>'FluentCart','fluentcommunity'=>'FluentCommunity','fluentcrm'=>'FluentCRM','merchant'=>'Merchant for WooCommerce','wpcode'=>'WPCode','sugar-calendar'=>'Sugar Calendar','optinmonster'=>'OptinMonster companion workflow','botiga'=>'Botiga');$out=array();foreach($slugs as$slug=>$title)$out[$slug]=array('slug'=>$slug,'title'=>$title,'min_wordpress'=>'6.0','min_wpvibe'=>'1.0.0','path'=>'skills/'.$slug.'.md','source'=>'builtin-1.3');return $out;}
	public static function saved(){ $s=get_option(self::OPTION,array());return is_array($s)?$s:array();}
	public static function metadata(){return array_merge(WPVDMCP_Skills::list_metadata(),array_values(self::extra_catalog()),self::saved_metadata());}
	private static function saved_metadata(){return array_values(array_map(function($s){unset($s['instructions']);if(isset($s['reference_files'])){$s['reference_files']=array_map(function($r){return array('name'=>$r['name'],'mime_type'=>$r['mime_type'],'bytes'=>strlen($r['content']));},(array)$s['reference_files']);}$s['source']='local';return $s;},self::saved()));}
	public static function load($slug){$slug=sanitize_key($slug);$saved=self::saved();if(isset($saved[$slug])){$meta=array_diff_key($saved[$slug],array('instructions'=>true,'reference_files'=>true));return array('skill'=>$slug,'metadata'=>$meta,'instructions'=>$saved[$slug]['instructions'],'reference_files'=>(array)($saved[$slug]['reference_files']??array()));}$extra=self::extra_catalog();if(isset($extra[$slug])){$path=dirname(__DIR__).'/'.$extra[$slug]['path'];if(!is_readable($path))return new WP_Error('skill_file_missing','Skill file missing.',array('status'=>500));return array('skill'=>$slug,'metadata'=>$extra[$slug],'instructions'=>trim((string)file_get_contents($path)));}return WPVDMCP_Skills::load($slug);}
	public static function instructions(){$out=WPVDMCP_Tools::skills();foreach(self::extra_catalog()as$slug=>$meta){$l=self::load($slug);if(!is_wp_error($l))$out[$slug]=$l['instructions'];}foreach(self::saved()as$slug=>$meta)$out[$slug]=$meta['instructions'];return $out;}
	public static function definitions(){return array(self::tool('list_skills','List built-in and locally saved workflow skills.',array()),self::tool('load_skill','Load a built-in or locally saved workflow skill.',array('skill'=>array('type'=>'string','enum'=>array_values(array_unique(array_merge(array_keys(WPVDMCP_Skills::catalog()),array_keys(self::extra_catalog()),array_keys(self::saved())))),'description'=>'Skill identifier.','_required'=>true))),self::tool('create_skill','Create a local persistent workflow skill. Requires approval.',self::write_props(false)),self::tool('update_skill','Update a local persistent workflow skill. Requires approval.',self::write_props(true)),self::tool('delete_skill','Delete a local persistent workflow skill. Built-in skills are immutable. Requires approval.',array('slug'=>self::strp('Saved skill slug.',true),'approval_id'=>self::strp('One-time approval ID.'))));}
	public static function handles($name){foreach(self::definitions()as$d){if($d['name']===$name)return true;}return false;}
	public static function execute($name,$args){$args=is_array($args)?$args:array();if('list_skills'===$name)return array('skills'=>self::metadata());if('load_skill'===$name)return self::load($args['skill']??'');if('create_skill'===$name)return self::write('create',$args);if('update_skill'===$name)return self::write('update',$args);if('delete_skill'===$name)return self::write('delete',$args);return new WP_Error('unknown_skill_tool','Unknown saved-skill tool.',array('status'=>404));}
	private static function write($action,$args){$slug=sanitize_key($args['slug']??'');if(!$slug)return new WP_Error('invalid_skill_slug','Skill slug is required.',array('status'=>400));if(isset(WPVDMCP_Skills::catalog()[$slug])||isset(self::extra_catalog()[$slug]))return new WP_Error('builtin_skill_immutable','Built-in skills cannot be changed by saved-skill tools.',array('status'=>409));$skills=self::saved();if('create'===$action&&isset($skills[$slug]))return new WP_Error('skill_exists','Saved skill already exists.',array('status'=>409));if(('update'===$action||'delete'===$action)&&!isset($skills[$slug]))return new WP_Error('skill_not_found','Saved skill not found.',array('status'=>404));$title=sanitize_text_field($args['title']??($skills[$slug]['title']??$slug));$description=sanitize_text_field($args['description']??($skills[$slug]['description']??''));if(strlen($description)>300)return new WP_Error('invalid_skill_description','Skill description must be at most 300 bytes.',array('status'=>400));$instructions=trim((string)($args['instructions']??($skills[$slug]['instructions']??'')));if('delete'!==$action&&(!$instructions||strlen($instructions)>self::MAX_BYTES))return new WP_Error('invalid_skill_instructions','Skill instructions are required and must be at most 20000 bytes.',array('status'=>400));$refs=array_key_exists('reference_files',$args)?self::sanitize_references($args['reference_files']):($skills[$slug]['reference_files']??array());if(is_wp_error($refs))return $refs;if('create'===$action&&count($skills)>=self::MAX_SKILLS)return new WP_Error('skill_limit','Saved skill limit reached.',array('status'=>409));$payload=array('action'=>$action,'slug'=>$slug,'title'=>$title,'description'=>$description,'instructions_hash'=>hash('sha256',$instructions),'references_hash'=>hash('sha256',wp_json_encode($refs)));$approval=self::approve($action.'_skill',$payload,$args);if(is_array($approval)||is_wp_error($approval))return $approval;if('delete'===$action){unset($skills[$slug]);update_option(self::OPTION,$skills,false);return array('status'=>'deleted','slug'=>$slug);}$record=array('slug'=>$slug,'title'=>$title,'description'=>$description,'min_wordpress'=>'6.0','min_wpvibe'=>'1.0.0','version'=>(int)($skills[$slug]['version']??0)+1,'instructions'=>$instructions,'reference_files'=>$refs);$skills[$slug]=$record;update_option(self::OPTION,$skills,false);return array('status'=>$action.'d','skill'=>$record);}
	private static function sanitize_references($refs){
		if(null===$refs)return array();if(!is_array($refs))return new WP_Error('invalid_skill_references','reference_files must be an array.',array('status'=>400));
		if(count($refs)>self::MAX_REFERENCE_FILES)return new WP_Error('skill_reference_limit','A saved skill can include at most 10 reference files.',array('status'=>400));
		$allowed=array('text/plain','text/markdown','text/csv','application/json');$out=array();
		foreach($refs as $ref){if(!is_array($ref))return new WP_Error('invalid_skill_reference','Each reference file must be an object.',array('status'=>400));$name=sanitize_file_name($ref['name']??'');$mime=sanitize_text_field($ref['mime_type']??'text/plain');$content=(string)($ref['content']??'');if(!$name||!in_array($mime,$allowed,true)||strlen($content)>self::MAX_REFERENCE_BYTES)return new WP_Error('invalid_skill_reference','Reference files require a safe text filename/MIME and at most 50000 bytes each.',array('status'=>400));$out[]=array('name'=>$name,'mime_type'=>$mime,'content'=>$content);}
		return $out;
	}
	private static function approve($op,$payload,$args){if(WPVDMCP_Approvals::bypass_enabled())return true;$id=(string)($args['approval_id']??'');if(!$id){$r=WPVDMCP_Approvals::request($op,$payload,$op);if(is_wp_error($r))return $r;return array_merge($r,array('status'=>'approval_required'));}return WPVDMCP_Approvals::consume($id,$op,$payload);}
	private static function write_props($updating){return array('slug'=>self::strp('Saved skill slug.',true),'title'=>self::strp('Skill title.',!$updating),'description'=>self::strp('One-line description.'),'instructions'=>self::strp('Workflow instructions.',!$updating),'reference_files'=>array('type'=>'array','items'=>array('type'=>'object','properties'=>array('name'=>array('type'=>'string'),'mime_type'=>array('type'=>'string'),'content'=>array('type'=>'string')),'required'=>array('name','mime_type','content'),'additionalProperties'=>false),'description'=>'Up to 10 bounded text reference files.'),'approval_id'=>self::strp('One-time approval ID.'));}
	private static function tool($name,$description,$props){$required=array();foreach($props as$k=>&$p){if(!empty($p['_required'])){$required[]=$k;unset($p['_required']);}}unset($p);$schema=array('type'=>'object','properties'=>(object)$props,'additionalProperties'=>false);if($required)$schema['required']=$required;return array('name'=>$name,'description'=>$description,'inputSchema'=>$schema);}private static function strp($d,$r=false){return array('type'=>'string','description'=>$d,'_required'=>$r);}
}
