<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
final class WPVDMCP_Parity_Skills {
	const OPTION='wpvdmcp_saved_skills';const MAX_SKILLS=50;const MAX_BYTES=20000;
	public static function extra_catalog(){$slugs=array('kadence'=>'Kadence Blocks','generatepress'=>'GeneratePress / GP Premium','generateblocks'=>'GenerateBlocks','editable-fields'=>'Editable fields','block-validation'=>'Validated block output','saved-skills'=>'Saved local skills','pdf-media'=>'PDF and media intelligence','site-intelligence'=>'Site intelligence','live-reload'=>'Live reload','lighthouse'=>'Lighthouse / performance audit providers','image-search'=>'Stock image search providers');$out=array();foreach($slugs as$slug=>$title)$out[$slug]=array('slug'=>$slug,'title'=>$title,'min_wordpress'=>'6.0','min_wpvibe'=>'1.0.0','path'=>'skills/'.$slug.'.md','source'=>'builtin-1.2');return $out;}
	public static function saved(){ $s=get_option(self::OPTION,array());return is_array($s)?$s:array();}
	public static function metadata(){return array_merge(WPVDMCP_Skills::list_metadata(),array_values(self::extra_catalog()),self::saved_metadata());}
	private static function saved_metadata(){return array_values(array_map(function($s){unset($s['instructions']);$s['source']='local';return $s;},self::saved()));}
	public static function load($slug){$slug=sanitize_key($slug);$saved=self::saved();if(isset($saved[$slug]))return array('skill'=>$slug,'metadata'=>array_diff_key($saved[$slug],array('instructions'=>true)),'instructions'=>$saved[$slug]['instructions']);$extra=self::extra_catalog();if(isset($extra[$slug])){$path=dirname(__DIR__).'/'.$extra[$slug]['path'];if(!is_readable($path))return new WP_Error('skill_file_missing','Skill file missing.',array('status'=>500));return array('skill'=>$slug,'metadata'=>$extra[$slug],'instructions'=>trim((string)file_get_contents($path)));}return WPVDMCP_Skills::load($slug);}
	public static function instructions(){$out=WPVDMCP_Tools::skills();foreach(self::extra_catalog()as$slug=>$meta){$l=self::load($slug);if(!is_wp_error($l))$out[$slug]=$l['instructions'];}foreach(self::saved()as$slug=>$meta)$out[$slug]=$meta['instructions'];return $out;}
	public static function definitions(){return array(self::tool('list_skills','List built-in and locally saved workflow skills.',array()),self::tool('load_skill','Load a built-in or locally saved workflow skill.',array('skill'=>array('type'=>'string','enum'=>array_values(array_unique(array_merge(array_keys(WPVDMCP_Skills::catalog()),array_keys(self::extra_catalog()),array_keys(self::saved())))),'description'=>'Skill identifier.','_required'=>true))),self::tool('create_skill','Create a local persistent workflow skill. Requires approval.',self::write_props(false)),self::tool('update_skill','Update a local persistent workflow skill. Requires approval.',self::write_props(true)),self::tool('delete_skill','Delete a local persistent workflow skill. Built-in skills are immutable. Requires approval.',array('slug'=>self::strp('Saved skill slug.',true),'approval_id'=>self::strp('One-time approval ID.'))));}
	public static function handles($name){foreach(self::definitions()as$d){if($d['name']===$name)return true;}return false;}
	public static function execute($name,$args){$args=is_array($args)?$args:array();if('list_skills'===$name)return array('skills'=>self::metadata());if('load_skill'===$name)return self::load($args['skill']??'');if('create_skill'===$name)return self::write('create',$args);if('update_skill'===$name)return self::write('update',$args);if('delete_skill'===$name)return self::write('delete',$args);return new WP_Error('unknown_skill_tool','Unknown saved-skill tool.',array('status'=>404));}
	private static function write($action,$args){$slug=sanitize_key($args['slug']??'');if(!$slug)return new WP_Error('invalid_skill_slug','Skill slug is required.',array('status'=>400));if(isset(WPVDMCP_Skills::catalog()[$slug])||isset(self::extra_catalog()[$slug]))return new WP_Error('builtin_skill_immutable','Built-in skills cannot be changed by saved-skill tools.',array('status'=>409));$skills=self::saved();if('create'===$action&&isset($skills[$slug]))return new WP_Error('skill_exists','Saved skill already exists.',array('status'=>409));if(('update'===$action||'delete'===$action)&&!isset($skills[$slug]))return new WP_Error('skill_not_found','Saved skill not found.',array('status'=>404));$title=sanitize_text_field($args['title']??($skills[$slug]['title']??$slug));$instructions=trim((string)($args['instructions']??($skills[$slug]['instructions']??'')));if('delete'!==$action&&(!$instructions||strlen($instructions)>self::MAX_BYTES))return new WP_Error('invalid_skill_instructions','Skill instructions are required and must be at most 20000 bytes.',array('status'=>400));if('create'===$action&&count($skills)>=self::MAX_SKILLS)return new WP_Error('skill_limit','Saved skill limit reached.',array('status'=>409));$payload=array('action'=>$action,'slug'=>$slug,'title'=>$title,'instructions_hash'=>hash('sha256',$instructions));$approval=self::approve($action.'_skill',$payload,$args);if(is_array($approval)||is_wp_error($approval))return $approval;if('delete'===$action){unset($skills[$slug]);update_option(self::OPTION,$skills,false);return array('status'=>'deleted','slug'=>$slug);}$record=array('slug'=>$slug,'title'=>$title,'min_wordpress'=>'6.0','min_wpvibe'=>'1.0.0','version'=>(int)($skills[$slug]['version']??0)+1,'instructions'=>$instructions);$skills[$slug]=$record;update_option(self::OPTION,$skills,false);return array('status'=>$action.'d','skill'=>$record);}
	private static function approve($op,$payload,$args){if(WPVDMCP_Approvals::bypass_enabled())return true;$id=(string)($args['approval_id']??'');if(!$id){$r=WPVDMCP_Approvals::request($op,$payload,$op);if(is_wp_error($r))return $r;return array_merge($r,array('status'=>'approval_required'));}return WPVDMCP_Approvals::consume($id,$op,$payload);}
	private static function write_props($updating){return array('slug'=>self::strp('Saved skill slug.',true),'title'=>self::strp('Skill title.',!$updating),'instructions'=>self::strp('Workflow instructions.',!$updating),'approval_id'=>self::strp('One-time approval ID.'));}
	private static function tool($name,$description,$props){$required=array();foreach($props as$k=>&$p){if(!empty($p['_required'])){$required[]=$k;unset($p['_required']);}}unset($p);$schema=array('type'=>'object','properties'=>(object)$props,'additionalProperties'=>false);if($required)$schema['required']=$required;return array('name'=>$name,'description'=>$description,'inputSchema'=>$schema);}private static function strp($d,$r=false){return array('type'=>'string','description'=>$d,'_required'=>$r);}
}
